import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Header from '../Components/Header'
import Navbar from '../Components/Navbar'
import ConsultWithStudent from '../Components/ConsultWithStudent'
import UniversityLogo from '../Components/UniversityLogo'
import NeedSomething from '../Components/NeedSomething'
import WhatGreat from '../Components/WhatGreat'
import FindTopConsultant from '../Components/FindTopConsultant'
import WhyMillions from '../Components/WhyMillions'
import WhatStudents from '../Components/WhatStudents'
import InsightBlogs from '../Components/InsightBlogs'
import Footer from '../Components/Footer'
// import Script from 'next/script'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Consultant Services</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous" />
        {/* <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script> */}

      </Head>
      <main >
  
      </main>
      <Header />
      <Navbar />
      <ConsultWithStudent />
      <UniversityLogo />
      <NeedSomething />
      <WhatGreat />
      <FindTopConsultant />
      <WhyMillions />
      <WhatStudents />
      <InsightBlogs />
      <Footer />
    </>
  )
}
