import Head from 'next/head'
// import Image from 'next/image'
import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'
import Header from '../components/Header'
import Menubar from '../components/Menubar'
import LandingPageBanner from '../components/LandingPageBanner'
import NeedSomethingDone from '../components/NeedSomethingDone'
import WhatGreatAboutIt from '../components/WhatGreatAboutIt'
import InsightsBlogs from '../components/InsightsBlogs'
import FindTopConsultant from '../components/FindTopConsultant'
import WhatStudentSay from '../components/WhatStudentSay'
import Footer from '../components/Footer'
import WhyStudentChooseUs from '../components/WhyStudentChooseUs'
import MobileMenubar from '../components/MobileMenubar'
import University from '../components/University'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Cohorten</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Menubar />
      <MobileMenubar />
      <LandingPageBanner />
      <University />
      <NeedSomethingDone />
      <WhatGreatAboutIt />
      <FindTopConsultant />
      <WhyStudentChooseUs />
      <WhatStudentSay />
      <InsightsBlogs />
      <Footer />






    </>
  )
}
